before_script:
  - export ANDROID_HOME="$HOME/Library/Android/sdk"
  - bundle install

stages:
  - build
  - test
  - quality_assurance
  - deploy

image: blang/latex
build:
  script:
    - latexmk -pdf -cd docs/dissertation.tex
  artifacts:
    paths:
      - "*.pdf"

build_job:
  stage: build
  script:
    - ./gradlew clean assembleRelease
  artifacts:
    paths:
      - app/build/outputs

 unit_tests:
  stage: test
  script:
    - ./gradlew test
  artifacts:
    name: "reports_${CSB-Project}_${dev-testing}"
    when: on_failure
    expire_in: 4 days
    paths:
      - app/build/reports/tests/

instrumentation_tests:
  stage: test
  script:
    - emulator -avd testAVD -no-audio -no-window &
    - ./ci/android-wait-for-emulator.sh
    - adb devices
    - adb shell settings put global window_animation_scale 0 &
    - adb shell settings put global transition_animation_scale 0 &
    - adb shell settings put global animator_duration_scale 0 &
    - adb shell input keyevent 82 &
    - ./gradlew connectedAndroidTest
    - ./ci/stop-emulators.sh
  artifacts:
    name: "reports_${CI_PROJECT_NAME}_${CI_BUILD_REF_NAME}"
    when: on_failure
    expire_in: 4 days
    paths:
      - app/build/reports/androidTests/connected/

static_analysis:
  stage: quality_assurance
  script:
    - ./gradlew lint
    - ./gradlew checkstyle
    - ./gradlew pmd
    - ./gradlew findbugs
  artifacts:
    name: "reports_${CSB-Project}_${dev-testing}"
    when: on_failure
    expire_in: 4 days
    paths:
      - app/build/reports/

deploy_internal:
  stage: deploy
  script:
    - bundle exec fastlane android deploy_lane
  when: manual
