# image: blang/latex
# build:
#   script:
#     - latexmk -pdf -cd docs/dissertation.tex
#   artifacts:
#     paths:
#       - "*.pdf"

image: openjdk:8-jdk

variables:
  ANDROID_COMPILE_SDK: "26"
  ANDROID_BUILD_TOOLS: "26.0.2"
  ANDROID_SDK_TOOLS: "24.4.1"

before_script:
  - cd ./MyPHR
  - mkdir $HOME/.android
  - echo 'count=0' > $HOME/.android/repositories.cfg
  - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-${ANDROID_SDK_TOOLS_REV}.zip
  - mkdir $PWD/android-sdk-linux
  - unzip -qq android-sdk.zip -d $PWD/android-sdk-linux
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=$PATH:$ANDROID_HOME/platform-tools/:$ANDROID_NDK_HOME
  - echo y | $ANDROID_HOME/tools/bin/sdkmanager --update
  - echo y | $ANDROID_HOME/tools/bin/sdkmanager 'tools'
  - echo y | $ANDROID_HOME/tools/bin/sdkmanager 'platform-tools'
  - echo y | $ANDROID_HOME/tools/bin/sdkmanager 'build-tools;'$ANDROID_BUILD_TOOLS
  - echo y | $ANDROID_HOME/tools/bin/sdkmanager 'platforms;android-'$ANDROID_COMPILE_SDK
  - echo y | $ANDROID_HOME/tools/bin/sdkmanager 'extras;android;m2repository'
  - echo y | $ANDROID_HOME/tools/bin/sdkmanager 'extras;google;google_play_services'
  - echo y | $ANDROID_HOME/tools/bin/sdkmanager 'extras;google;m2repository'
  - chmod +x ./gradlew


stages:
  - build
  - test
  #- quality_assurance

build:
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
    - app/build/outputs/

unitTests:
  stage: test
  script:
    - ./gradlew test

instrumentation_tests:
  stage: test
  allow_failure: true
  when: manual
  script:
    - apt-get update
    - apt-get install  -y --no-install-recommends file libmagic1 libglu1-mesa mesa-utils libpci3 pciutils libpulse0
    - wget --quiet --output-document=android-wait-for-emulator https://raw.githubusercontent.com/travis-ci/travis-cookbooks/0f497eb71291b52a703143c5cd63a217c8766dc9/community-cookbooks/android-sdk/files/default/android-wait-for-emulator
    - chmod +x android-wait-for-emulator
    - echo y | $ANDROID_HOME/tools/bin/sdkmanager "system-images;android-${ANDROID_COMPILE_SDK};google_apis;x86_64"
    - echo no | $ANDROID_HOME/tools/bin/avdmanager -v create avd -n test -k "system-images;android-${ANDROID_COMPILE_SDK};google_apis;x86_64" --tag "google_apis" --abi "x86_64"
    - SHELL=/bin/bash $ANDROID_HOME/tools/emulator -avd test -no-window -no-audio &
    - ./android-wait-for-emulator
    - adb shell input keyevent 82
    - ./gradlew cAT
  artifacts:
    paths:
      - app/build/reports/androidTests/

# static_analysis:
#   stage: quality_assurance
#   script:
#     - ./gradlew lint
#     - ./gradlew checkstyle
#     - ./gradlew pmd
#     - ./gradlew findbugs
#   artifacts:
#     name: "reports_${CI_PROJECT_NAME}_${CI_BUILD_REF_NAME}"
#     when: on_failure
#     expire_in: 4 days
#     paths:
#       - app/build/reports/